from __future__ import annotations

import json
from pathlib import Path

from .models import KnowledgeChunk, RetrievedChunk
from .utils import tokenize, write_json


class KnowledgeBase:
    def __init__(self, chunks: list[KnowledgeChunk] | None = None) -> None:
        self.chunks = chunks or []

    @classmethod
    def from_json(cls, path: Path) -> "KnowledgeBase":
        if not path.exists():
            return cls()
        raw = json.loads(path.read_text(encoding="utf-8"))
        chunks = [KnowledgeChunk(**item) for item in raw.get("chunks", raw)]
        return cls(chunks)

    def to_json(self, path: Path) -> None:
        write_json(path, {"chunks": self.chunks})

    def add_text(
        self,
        text: str,
        *,
        source: str,
        metadata: dict[str, str] | None = None,
        chunk_size: int = 900,
    ) -> None:
        metadata = metadata or {}
        paragraphs = [part.strip() for part in text.splitlines() if part.strip()]
        buffer: list[str] = []
        current_len = 0
        index = len(self.chunks) + 1

        for paragraph in paragraphs:
            if current_len + len(paragraph) > chunk_size and buffer:
                self._append_chunk(index, source, "\n".join(buffer), metadata)
                index += 1
                buffer = []
                current_len = 0
            buffer.append(paragraph)
            current_len += len(paragraph)

        if buffer:
            self._append_chunk(index, source, "\n".join(buffer), metadata)

    def search(self, query: str, *, top_k: int = 5) -> list[RetrievedChunk]:
        query_terms = set(expand_terms(tokenize(query)))
        scored: list[RetrievedChunk] = []

        for chunk in self.chunks:
            metadata_text = " ".join(str(value) for value in chunk.metadata.values())
            chunk_terms = set(expand_terms(tokenize(chunk.text + " " + metadata_text)))
            if not chunk_terms:
                continue
            overlap = query_terms.intersection(chunk_terms)
            score = len(overlap) / max(len(query_terms), 1)
            if score:
                scored.append(RetrievedChunk(chunk=chunk, score=score))

        return sorted(scored, key=lambda item: item.score, reverse=True)[:top_k]

    def _append_chunk(
        self, index: int, source: str, text: str, metadata: dict[str, str]
    ) -> None:
        chunk_metadata = {"source": source, **metadata}
        self.chunks.append(
            KnowledgeChunk(chunk_id=f"{Path(source).stem}-{index:04d}", text=text, metadata=chunk_metadata)
        )


def expand_terms(terms: list[str]) -> list[str]:
    aliases = {
        "coordinate": ["position", "axis", "坐标", "轴"],
        "position": ["coordinate", "坐标"],
        "spindle": ["主轴", "speed"],
        "program": ["nc", "gcode", "程序"],
        "parameter": ["参数", "config"],
        "alarm": ["报警", "fault"],
        "status": ["state", "状态"],
        "traffic": ["流量", "packet", "capture"],
        "capture": ["pcap", "抓包", "流量"],
        "坐标": ["coordinate", "position", "axis"],
        "主轴": ["spindle", "speed"],
        "程序": ["program", "nc", "gcode"],
        "参数": ["parameter", "config"],
        "报警": ["alarm", "fault"],
        "状态": ["status", "state"],
        "流量": ["traffic", "packet", "capture"],
    }
    expanded = list(terms)
    for term in terms:
        expanded.extend(aliases.get(term, []))
    return expanded


def sample_knowledge() -> KnowledgeBase:
    chunks = [
        KnowledgeChunk(
            chunk_id="api-coordinate-0001",
            text=(
                "ReadPosition reads current X/Y/Z coordinates during CNC motion. "
                "Parameters: axis list, coordinate system, sample interval. "
                "Use it while an NC program is running."
            ),
            metadata={"type": "api", "interface": "ReadPosition", "scene": "coordinate_motion"},
        ),
        KnowledgeChunk(
            chunk_id="api-status-0001",
            text=(
                "ReadRunStatus returns idle, running, paused, completed, or alarm. "
                "Call it before, during, and after program execution."
            ),
            metadata={"type": "api", "interface": "ReadRunStatus", "scene": "program_state"},
        ),
        KnowledgeChunk(
            chunk_id="api-program-0001",
            text=(
                "UploadProgram, SelectProgram, StartProgram, and StopProgram control "
                "NC program lifecycle for simulator execution."
            ),
            metadata={"type": "api", "interface": "ProgramLifecycle", "scene": "program_state"},
        ),
        KnowledgeChunk(
            chunk_id="api-feed-0001",
            text=(
                "ReadFeedSpeed reads feed speed during movement. It is useful for "
                "traffic generated by coordinate and machining state changes."
            ),
            metadata={"type": "api", "interface": "ReadFeedSpeed", "scene": "coordinate_motion"},
        ),
        KnowledgeChunk(
            chunk_id="nc-motion-0001",
            text=(
                "A straight interpolation NC program can use G90 G01 moves over "
                "X, Y, and Z, with M03 spindle start and M30 program end."
            ),
            metadata={"type": "nc_template", "scene": "coordinate_motion"},
        ),
    ]
    return KnowledgeBase(chunks)

